---
- name:         Installeren wkhtmltox dependencies
  yum:          name={{ item }}
                state=present
  with_items:
   - xorg-x11-fonts-75dpi
   # https://github.com/KnpLabs/snappy/issues/162
   # Installeren extra font voor encoding probleem
   - urw-fonts

- name:         Installeren wkhtmltopdf
  yum:          name=http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-centos6-amd64.rpm
                state=present
  when:         'ansible_distribution == "CentOS" and ansible_distribution_major_version=="6"'

- name:         Installeren wkhtmltopdf
  yum:          name=http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-centos7-amd64.rpm
                state=present
  when:         'ansible_distribution == "CentOS" and ansible_distribution_major_version=="7"'
